config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root 'places#index'
    resources :places do
        resources :comments, only: :create
        resources :photos, only: :create
    end

    resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :place
    validates :message, presence: true
    validates :rating, presence: true
    after_create :send_comment_email
    paginates_per 4
    RATINGS = {
        'one star': '1_star',
        'two star': '2_stars',
        'three stars': '3_stars',
        'four stars': '4_stars',
        'five stars': '5_stars'
    }

    def humanized_rating
        RATINGS.invert[self.rating]
    end

    def send_comment_email
        NotificationMailer.comment_added(self).deliver_now
    end
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
    mount_uploader :picture, PictureUploader
    belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
    paginates_per 5
    belongs_to :user
    has_many :comments
    has_many :photos
    geocoded_by :address
    after_validation :geocode
    validates :name, presence: true
    validates :address, presence: true
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :places
    has_many :comments
     paginates_per 4
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    


    def create
        @place = Place.find(params[:place_id])
        
        @place.comments.create(comment_params.merge(user: current_user))
        
        redirect_to place_path(@place)  
    end

    

    private

    def comment_params
        params.require(:comment).permit(:message, :rating)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
 before_action :authenticate_user!

 def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params)
    redirect_to place_path(@place)
end

private

def photo_params
    params.require(:photo).permit(:caption, :picture)
end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    def index
        @places = Place.all.page(params[:page])      
    end

  

    def new
        @place = Place.new
    end  

    def create
        @place = current_user.places.create(place_params)
        if @place.valid?
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        @place = Place.find(params[:id])
        if @place.user != current_user
            return render plain: 'Not allowed', status: :forbidden
        end
        @place.update_attributes(place_params)
        if @place.valid?     
            flash[:alert] = 'Update successful'
            redirect_to place_path(@place)
        else
            render :edit, status: :unprocessable_entity
        end       
    end

    def show
        @place = Place.find(params[:id])
        @comment = Comment.new
        @photo = Photo.new
    end

    def edit
        @place = Place.find(params[:id])
        if @place.user != current_user
            return render plain: 'Not allowed', status: :forbidden
        end       
    end  

    def destroy
        @place = Place.find(params[:id])
        if @place.user != current_user
            return render plain: 'Not allowed', status: :forbidden
        end
        @place.destroy
        redirect_to root_path
    end
    
    private

    def place_params
        params.require(:place).permit(:name, :description, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :user_authorization

 
  def show
    @user = User.find(params[:id])
    @usercomments = @user.comments.page(params[:page]).per(4)
  end

   private

     def user_authorization
        redirect_to(root_url) unless current_user.id.to_s == params[:id]
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_include_tag "//maps.google.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}" %>

    <title>Nomster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
  
  <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
      </li>
      <li class="nav-item">
             <%= link_to new_place_path, class: 'nav-link' do%>
         <i class="fa fa-plus-circle"></i>
          New Place
          <% end %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
         <%= link_to 'Sign out',  destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <li class="nav-item">
         <%= link_to 'User Dashboard', user_path(current_user), class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
  </div>
</nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  
  </body>
   <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
    <h1>Edit Your Place </h1><br />
    <%= simple_form_for @place do |f| %>
    <%= f.input :name, label: "Name" %>
    <%= f.input :address, label: "Address change?" %>
    <%= f.input :description, label: "Please describe your experience" %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/places/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <title>Nomster</title>
</head>
<body>
<div class = "booyah-box banner col-10 offset-1">
<div class = "row">
  <div class = "col-sm">
    <div id="carouselExampleIndicators" class="carousel" data-ride="carousel" style='margin-top: 10px'>
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner text-align-center" role="listbox">
        <div class="carousel-item active center">
          <%= image_tag 'slider1.jpg', class: 'img-fluid caro' %> 
        </div>
        <div class="carousel-item center-block">
          <%= image_tag 'slider2.jpg', class: 'img-fluid caro'  %> 
        </div>
        <div class="carousel-item center-block">
          <%= image_tag 'slider3.jpg', class: 'img-fluid caro' %> 
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div class = "col-sm">
    <h1 id="logo"> Nomster </h1>
    <br />
    <p id="blurb">Your only sensible destination for snarky reviewers, unedecated critiques, and just trying to find somewhere decent to eat.</p>
  </div>
</div>
</div>
<div class = clear>

<% @places.each do |place| %>
  <div class='booyah-box col-10 offset-1'>
     <div class = "row">
       <div class = "col">
    <h1><%= link_to place.name, place_path(place), data: { turbolinks: false } %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p>
    <% if place.user.present? %>
    <small><%= place.user.email %></small>
      </div>
      <% end %>
        <div class="col">
          <%if place.photos.last.present? %>
       <%= image_tag place.photos.last.picture.url, class: "photopreview" %>
       <% end %>
      <% if place.comments.present? %>   
        <blockquote>
          <% if place.comments.first.humanized_rating.present? %>
          <b><%= place.comments.first.humanized_rating %></b> -
          <% end %>
          <%= place.comments.first.message %>
          <small><%= place.comments.first.user.email %></small>
        </blockquote>
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
          <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
        <% end %>
      </div>
    </div>
  </div>
<% end %>


<div class="offset-5">
 <%= paginate @places %>
</div>

</body>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
    <h1>Enter place detais</h1>
    <%= simple_form_for @place do |f| %>
    <%= f.input :name, label: "Place you would like to add", placeholder: "Some kitchen" %>
    <%= f.input :address, label: "Where are they located?", placeholder: "123 That Avenue" %>
    <%= f.input :description, label: "Please describe your experience", placeholder: "Mediocre at best" %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/places/show.html.erb
<div class='booyah-box box-fill'>
  <h1><%= @place.name %></h1><br />
  <% if @place.latitude.present? && @place.longitude.present? %>
  <script>

    function initMap() {
      var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GEOCODER_API_KEY"] %>&callback=initMap"></script>
<% end %>


    <div id="map"></div>

<i><%= @place.address %></i><br /><br />    
<% @place.photos.each do |photo| %>
<div class="item">
  <img class="photopreview" <%= image_tag photo.picture.url unless photo.picture.nil? %> 
  <span class="caption"><%= photo.caption %></span>
</div>  
<% end %>
<br /><br />
<div class = "booyah-box col-10 offset-1">
  <p><%= @place.description %></p><br />
</div>
</div>

<div class="clear"></div>

<div class="float-right">
  <% if current_user && current_user == @place.user %>
  <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
  <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this place?'}, class: 'btn btn-primary' %>
  <% end %>
</div>

<div class="clear"></div>


<div class="booyah-box col-10 offset-1">
  <div class="float-left"><h1>Comments</h1></div>
  <div class="clear"></div>
  <div class="row">
    <% @place.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <blockquote>
        <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <br />
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
    <% end %>
  </div>
</div>

<!-- Comment Button trigger modal -->
<div class="float-right">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#commentModal">
    Add a comment
  </button>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#photoModal">
    Add a photo
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a Comment</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <%= f.input :message %>
        <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit 'Add a Comment', class: 'btn btn-primary' %></button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="clear"></div>


<!-- Photo Modal -->
<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a photo</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <%= f.input :caption %>
        <%= f.input :picture %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit 'Add a photo', class: 'btn btn-primary' %></button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="booyah-box col-10 offset-1">
  <div class="row">
    <div class="column-2">
      <%= image_tag 'defaultav.png', class: 'photopreview'%>
    </div>
    <div class="column">
      <h3>Welcome to your dashboard, <%= @user.email %></h3> <br />
      <h4> Member since: <%= @user.created_at.strftime("%B %d, %Y")%> </h4>
      <h4><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</h4>
    </div>
    <div class="column">
    </div>
  </div> <!-- Row closer -->
</div> <!-- Box closer -->

<div class="clear"></div>

<div class="row">
  <div class="booyah-box col-5" style="margin: 5px 2.5% 5px 5%">
    <div class="float-left"><h3>Comments - <small><%= @user.comments.count %> total</small></h3></div><br /><br />

    <% @user.comments.each do |comment| %>
    <h4 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h4>
    <blockquote>
      <% if comment.humanized_rating.present? %>
      <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
      <br />
      <small><%= comment.user.email %></small>
    </blockquote>
    <% end %>   
  </div>
  <div class="col-5">
    <div class="float-left"><h3>Places - <small><%= @user.places.count %> added</small></h3></div><br /><br />
    <% @user.places.each do |place| %>
    <div class="booyah-box" >

    <h1><%= link_to place.name, place_path(place), data: { turbolinks: false } %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p>
    <%if place.photos.last.present? %>
    <%= image_tag place.photos.last.picture.url, class: "photopreview" %>v
    <% end %>
    </div>
    <% end %>
  </div>
</div> <!-- Row Closer -->